#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: ./stack push <image_name> <dockerhub_username>"
    exit 1
fi

IMAGE_NAME=$1
DOCKERHUB_USERNAME=$2

docker tag "$IMAGE_NAME" "$DOCKERHUB_USERNAME/$IMAGE_NAME"
docker push "$DOCKERHUB_USERNAME/$IMAGE_NAME" 